### ISSUE TITLE
generated tracking code seems to be incorrect

### ISSUE THREAD

**Issue by cboesch** [pebosi/ilias-piwik#1]
the tracking code generated by the plugin seems to be faulty.

this is generated:
var u=(("https:" == document.location.protocol) ? "https://piwik.domain.at/piwik" : "http://piwik.domain.at/piwik";
in my opinion it should be this way (closing bracket at the end):
var u=(("https:" == document.location.protocol) ? "https://piwik.domain.at/piwik" : "http://piwik.domain.at/piwik");

and the trailing slash is automatically removed from the entered piwik url. so this line is also wrong:
g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
should be (with slash /piwik.js):
g.defer=true; g.async=true; g.src=u+"/piwik.js"; s.parentNode.insertBefore(g,s);

**Comment by pebosi** [comment]
Fixed in today's commit. Updating the code to use protocol relative url.
