### ISSUE TITLE
New Plugin Version?

### ISSUE THREAD

**Issue by pattylg** [pebosi/ilias-piwik#4]
Unfortunately, the plugin does not work with an ILIAS 5.4 or higher. Is there a chance that you can do that? Merci

**Comment by kalamun** [comment]
Apparently this repo has been abandoned, so I forked it and modified in order to extend the supported versions up to 6.13.
Here my new repo: https://github.com/kalamun/ilias-piwik

I will extend the support to ILIAS 7 and 8 in the next weeks.

**Comment by pebosi** [comment]
Created a new version
